services:
  - type: web
    name: easyloading
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: easyloading-disk
      mountPath: /opt/render/project/src
      sizeGB: 1

