services:
  - type: web
    name: easy2-0
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: easyloading
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        fromService:
          type: web
          name: easy2-0
          property: port
